name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'ğŸŒ client'
    label: 'client'
  - title: 'ğŸ‡°ğŸ‡· client2'
    label: 'client2'
  - title: 'ğŸ“‚ common'
    label: 'common'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
template: |
  ## Whatâ€™s Changed

  $CHANGES
